### ISSUE TITLE
createPdf` errored out - TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by geoff-maddock** [phoinixi/jsonresume-theme-stackoverflow#60]
Running into a timeout when using this theme, but other themes are working.  Anyone resolve this?
```
cutups@Hydra-PC:/mnt/c/Users/cutups/code/projects/geoff-maddock.github.io$ resume export resume.pdf --theme ./node_modules/jsonresume-theme-stackoverflow
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /usr/local/lib/node_modules/resume-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111 `createPdf` errored out

Done! Find your new .pdf resume at:
 /mnt/c/Users/cutups/code/projects/geoff-maddock.github.io/resume.pdf
```

**Comment by phoinixi** [comment]
Thanks for opening the issue this is on resume-cli, you can consider opening an issue there https://github.com/jsonresume/resume-cli


Although as workaround you can print your resume from the browser and instead of choosing a printer, you select "print to PDF", my theme do support dedicated styles for printing
